name: GitHub Action Test

on: push

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: update apt
        run: |
          sudo apt-get update
      - name: ubuntu version
        run: |
          cat /etc/os-release
      - name: install libmysql
        run: |
          sudo apt-get install -y mysql-client libmysqlclient-dev
