name: GitHub Action Test

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install libmysql
        run: |
          sudo apt-get install -y mysql-client libmysqlclient-dev
